CREATE database `sql_excercise`;

CREATE TABLE IF NOT EXISTS `sql_excercise`.`address` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `CITY` VARCHAR(255) NOT NULL,
  `COUNTRY` VARCHAR(255) NOT NULL,
  `STREET` VARCHAR(255) NOT NULL,
  `ZIPCODE` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID`));

CREATE TABLE IF NOT EXISTS `sql_excercise`.`food` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `CALORIES` INT NULL DEFAULT NULL,
  `ISVEGAN` BIT NOT NULL,
  `NAME` VARCHAR(255) NOT NULL,
  `PRICE` INT NOT NULL,
  PRIMARY KEY (`ID`));

CREATE TABLE IF NOT EXISTS `sql_excercise`.`menu` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Restaurant_ID` VARCHAR(255) NOT NULL,
  `FROMDATE` DATE NULL DEFAULT NULL,
  `TODATE` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`ID`));

CREATE TABLE IF NOT EXISTS `sql_excercise`.`menu_food` (
  `Menu_ID` INT NOT NULL,
  `Foods_ID` INT NOT NULL,
  PRIMARY KEY (`Menu_ID`, `Foods_ID`),
    FOREIGN KEY (`Menu_ID`)
    REFERENCES `sql_excercise`.`menu` (`ID`),
	FOREIGN KEY (`Foods_ID`)
    REFERENCES `sql_excercise`.`food` (`ID`));
;

CREATE TABLE IF NOT EXISTS `sql_excercise`.`restaurant` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(255) NOT NULL,
  `ADDRESS_ID` INT NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC),
    FOREIGN KEY (`ADDRESS_ID`)
    REFERENCES `sql_excercise`.`address` (`ID`));